disable scan exit code failures

diff --git a/.github/workflows/sast-apps.yml b/.github/workflows/sast-apps.yml
--- a/.github/workflows/sast-apps.yml
+++ b/.github/workflows/sast-apps.yml
@@ -43,7 +43,7 @@ jobs:
           name: kustomize
 
       - name: Kubescape scan
-        run: kubescape scan framework all kustomize.yaml --verbose --fail-threshold 0 --exclude-namespaces kube-system,kube-public
+        run: kubescape scan framework all kustomize.yaml --verbose --exclude-namespaces kube-system,kube-public # --fail-threshold 0
 
   kube-score:
     name: kube-score
@@ -62,4 +62,4 @@ jobs:
           name: kustomize
 
       - name: Calculate kube-score score
-        run: kube-score score kustomize.yaml --ignore-container-cpu-limit --ignore-container-memory-limit
+        run: kube-score score kustomize.yaml || exit 0
